version: '2'
services:
  mysql:
    container_name: ${APP_NAME}-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql


  phpmyadmin:
    container_name: ${APP_NAME}-phpadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
    restart: always
    links:
      - mysql:mysql
    ports:
      - ${MYSQL_PORT}:80

  wordpress:
    container_name: ${APP_NAME}-wordpress
    depends_on:
      - mysql
    image: ${WP_VERSION}
    links:
      - mysql
    ports:
      - ${WP_PORT}:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${DB_PREFIX}
    volumes:
      - ./wp-content:/var/www/html/wp-content

volumes:
  db_data:
    driver: local